#! bin/bash

echo "Instalando..."

sleep 4

sudo apt update
sudo apt install git
git clone https://github.com/kelebek333/rtl8188fu
sleep 2
sudo apt install dkms

sudo dkms add ./rtl8188fu
sudo dkms build rtl8188fu/1.0
sudo dkms install rtl8188fu/1.0
sudo cp ./rtl8188fu/firmware/rtl8188fufw.bin /lib/firmware/rtlwifi/
sleep 4

echo "Rebooting your computer..."

reboot
